import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    width: '100%',
    maxWidth: '900px',
    margin: '30px auto',
    padding: '24px',
    background: 'rgba(255,255,255,0.03)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: '12px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.3)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  title: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#FFD700',
  },
  subtitle: {
    fontSize: '13px',
    color: '#aaa',
  },
  rows: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '20px',
  },
  row: {
    display: 'flex',
    justifyContent: 'center',
    gap: '8px',
  },
  key: {
    minWidth: '56px',
    height: '70px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    background: 'rgba(0,0,0,0.6)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 8px rgba(0,0,0,0.4)',
  },
  keyChar: {
    fontSize: '32px',
    fontFamily: 'serif',
    fontWeight: 'bold',
    lineHeight: 1,
  },
  keyValue: {
    fontSize: '11px',
    color: '#999',
    fontFamily: 'monospace',
  },
  actions: {
    display: 'flex',
    gap: '12px',
    marginBottom: '12px',
  },
  actionBtn: {
    flex: 1,
    padding: '12px 16px',
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: '8px',
    color: '#ddd',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  info: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#666',
    padding: '12px',
    background: 'rgba(255,255,255,0.02)',
    borderRadius: '6px',
  },
};
